from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator

VALID_CATEGORIES = {
    "bug",
    "smell",
    "performance",
    "security",
    "refactor",
    "naming",
    "best_practice",
    "docs",
    "maintainability",
    "readability",
}

VALID_SEVERITIES = {"info", "warning", "error", "critical"}


class AIFinding(BaseModel):
    """Structured feedback finding generated by the AI Code Review Engine."""

    category: str = Field(
        ...,
        description="Type of issue: bug, smell, performance, security, refactor, naming, best_practice, docs, maintainability, readability",
    )
    severity: str = Field(..., description="Issue severity: info, warning, error, critical")
    summary: str = Field(..., max_length=200, description="Brief one-line summary of the recommendation")
    explanation: str = Field(..., description="Detailed explanation detailing the issue context and side-effects")
    recommendation: str = Field(..., description="Actionable guideline code suggestion mapping how to fix the warning")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model's confidence rating score (0.0 to 1.0)")
    file_reference: str = Field(..., description="Relative path of the codebase file containing the finding")
    function_reference: Optional[str] = Field(None, description="Optional function/method name containing the finding")
    line_reference: Optional[int] = Field(None, ge=1, description="Optional 1-indexed line number of the finding")

    model_config = ConfigDict(from_attributes=True, extra="ignore")

    @field_validator("category")
    @classmethod
    def validate_category(cls, val: str) -> str:
        lower_val = val.lower().strip()
        if lower_val not in VALID_CATEGORIES:
            raise ValueError(f"Category '{val}' is not supported. Must be one of: {list(VALID_CATEGORIES)}")
        return lower_val

    @field_validator("severity")
    @classmethod
    def validate_severity(cls, val: str) -> str:
        lower_val = val.lower().strip()
        if lower_val not in VALID_SEVERITIES:
            raise ValueError(f"Severity '{val}' is not supported. Must be one of: {list(VALID_SEVERITIES)}")
        return lower_val


class AIReviewResult(BaseModel):
    """Aggregated AI Code Review result housing summary metadata and findings."""

    summary: str = Field(..., description="Overall code quality summary and high-level feedback comments")
    findings: List[AIFinding] = Field(default_factory=list, description="List of granular code quality findings")

    model_config = ConfigDict(from_attributes=True, extra="ignore")
